# Generated by Django 2.0.7 on 2018-07-23 08:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250, validators=[django.core.validators.RegexValidator('^[a-zA-Z- ]*$', message='Only Letters allowed!')])),
                ('middle_name', models.CharField(blank=True, max_length=250, null=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z- ]*$', message='Only Letters allowed!')])),
                ('last_name', models.CharField(max_length=250, validators=[django.core.validators.RegexValidator('^[a-zA-Z- ]*$', message='Only Letters allowed!')])),
                ('email', models.EmailField(blank=True, max_length=250, null=True)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('sex', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], default='F', max_length=1)),
                ('date_of_birth', models.DateField()),
            ],
        ),
    ]
