# Generated by Django 2.0.7 on 2018-07-23 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20180723_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_number',
            field=models.CharField(default='Emp-0001', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
